### ISSUE TITLE
Summer2020 - Casbin.NET (Xianhe Tang) 

### ISSUE THREAD

**Issue by Sagilio** [casbin/Summer2020#14]
Summer2020 Project: https://isrc.iscas.ac.cn/summer2020/#/organisations/casbin (ID: 2008311)

![image](https://user-images.githubusercontent.com/42855245/86560857-def54300-bf91-11ea-9986-8d2907c99a4a.png)

Student: @Sagilio

Mentors: @huazhikui

IM Channel: TBD

Weekly reports will be appended as replies by the student.

**Comment by Sagilio** [comment]
The reports will also commit to https://forum.casbin.org/t/9 at now.

**Comment by hsluoyz** [comment]
Thanks!
