### ISSUE TITLE
Summer2020 - Casbin DashBoard (Xiaoyang Gu)

### ISSUE THREAD

**Issue by 438561537** [casbin/Summer2020#15]
Summer2020 Project: 
 https://isrc.iscas.ac.cn/summer2020/#/organisations/casbin(ID:2008312)
![dashboard](https://user-images.githubusercontent.com/41043187/86564373-b15fc800-bf98-11ea-83f3-2105e2a869bf.png)

Student: Xiaoyang Gu @438561537

Mentors:Helong Zhang @BetaCat0

IM Channel: TBD

Weekly reports will be appended as replies by the student.

**Comment by 438561537** [comment]
# Week1 （July 1-July 6）
## Weekly summary：
1. Studied the fundamental architecture of Beego. Modifying the routing method and the api.
2. Optimizing the web front-end by react+antd.
3. Studied the casbin policy.
## Before coding：
As the casbin is not responsible for User authentication, I think the dashboard needs to have a User authentication procedure to guarantee the security of the casbin platform.
## Next week：
1. Continue to optimize the web front-end.
2. Add the User authentication model for user management.
3. Implement some enforcement api.

**Comment by 438561537** [comment]
# Week1 （July 7-July 16）
## Weekly summary：
1. Fixed some bugs and  [issue 10](https://github.com/casbin/casbin-dashboard/issues/10) [issue 83](already merged)(https://github.com/casbin/casbin-dashboard/issues/83)(reviewing). Optimizing the web front-end.
2. Studied the Antd frame.
3. Changing the Layout of the UI.

## Next week：
1. Continue to optimize the web front-end. Add a policies table on dashboard.
2. Add the User authentication pages for user management.
3. Studied the elementUI and antd, choose a suitable front-end frame for future coding.

**Comment by hsluoyz** [comment]
Migrated to: https://forum.casbin.org/t/16
