### ISSUE TITLE
Summer2020 - Node Casbin (Zhang Hongbin)

### ISSUE THREAD

**Issue by zhmushan** [casbin/Summer2020#16]
Summer2020 Project: https://isrc.iscas.ac.cn/summer2020/#/organisations/casbin (ID: 2008310)
![image](https://user-images.githubusercontent.com/24505451/86793139-c1ad9b00-c09d-11ea-90e4-414f39a0cef6.png)
Student: @zhmushan

Mentors: @nodece 

Weekly reports will be appended as replies by the student.

**Comment by zhmushan** [comment]
Moved to: https://forum.casbin.org/t/8

**Comment by hsluoyz** [comment]
Thanks for supporting it!
